<a href="https://colab.research.google.com/github/N-Vincentia-Harshini-4/FML-lab/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([2,4,6,8])
print(a)

[2 4 6 8]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a[0])

2


In [ ]:
x=np.array([[2,4,6],[1,3,5],[6,8,9]])
print(x[2])

[6 8 9]


In [ ]:
x=np.array([[2,4,6],[1,3,5],[6,8,9]])
print(x)

[[2 4 6]
 [1 3 5]
 [6 8 9]]


In [ ]:
a=[[2,3,4],[5,6,7]]
b=np.asarray(a)
print(b)

[[2 3 4]
 [5 6 7]]


In [ ]:
a=[[2,3,4],[5,6,7]]
b=np.asarray(a,order="c")
print(b)

[[2 3 4]
 [5 6 7]]


In [ ]:
for i in np.nditer(b):
   print(i)

2
3
4
5
6
7


In [ ]:
a=b"Fundamentals of machine learning"
np.frombuffer(a)

array([6.19631637e+223, 1.33856863e-152, 1.27873526e-152, 1.69375270e+190])

In [ ]:
a=b"Fundamentals of machine learning"
np.frombuffer(a,dtype="S1")

array([b'F', b'u', b'n', b'd', b'a', b'm', b'e', b'n', b't', b'a', b'l',
       b's', b' ', b'o', b'f', b' ', b'm', b'a', b'c', b'h', b'i', b'n',
       b'e', b' ', b'l', b'e', b'a', b'r', b'n', b'i', b'n', b'g'],
      dtype='|S1')

In [ ]:
a=b"Fundamentals of machine learning"
np.frombuffer(a,dtype="S1",count=20)

array([b'F', b'u', b'n', b'd', b'a', b'm', b'e', b'n', b't', b'a', b'l',
       b's', b' ', b'o', b'f', b' ', b'm', b'a', b'c', b'h'], dtype='|S1')

In [ ]:
a=b"Fundamentals of machine learning"
np.frombuffer(a,dtype="S1",offset=12)

array([b' ', b'o', b'f', b' ', b'm', b'a', b'c', b'h', b'i', b'n', b'e',
       b' ', b'l', b'e', b'a', b'r', b'n', b'i', b'n', b'g'], dtype='|S1')

In [ ]:
a=[230,343,552,532]

In [ ]:
np.fromiter(a,dtype=int,count=3)

array([230, 343, 552])

In [ ]:
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [ ]:
a=np.zeros([4,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
(a)

array([0., 0., 0., 0.])

In [ ]:
a=np.zeros([3,4],dtype=float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a=np.zeros([5,3,4])
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
a=np.full([4,6],2)
print(a)

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [ ]:
a=np.full([4,4,6],8)
print(a)

[[[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]
  [8 8 8 8 8 8]]]


In [ ]:
a=np.random.rand(6,4)
print(a)

[[0.27060929 0.55606758 0.0642485  0.8853297 ]
 [0.84550446 0.23098766 0.04662638 0.25860805]
 [0.16381318 0.5021807  0.30016005 0.60691334]
 [0.6333911  0.93503391 0.17273041 0.17709823]
 [0.13800194 0.75462637 0.72450085 0.64840827]
 [0.1812171  0.85262109 0.0592355  0.09043292]]


In [ ]:
a=np.random.rand(6,6,4)
print(a)

[[[0.25467975 0.43043851 0.55335594 0.29426885]
  [0.47449041 0.28767066 0.01667852 0.8469509 ]
  [0.73690085 0.36355075 0.45144847 0.74887493]
  [0.42473897 0.59356552 0.45796778 0.44998005]
  [0.97062756 0.99334805 0.0611449  0.98641885]
  [0.64093699 0.23670462 0.15948305 0.1289984 ]]

 [[0.04841993 0.66822921 0.29172649 0.85342945]
  [0.21669632 0.45721583 0.30217827 0.40679586]
  [0.10765491 0.91205942 0.96888659 0.84373554]
  [0.97677557 0.80995938 0.26553788 0.74583598]
  [0.71314118 0.6604706  0.88105397 0.85621405]
  [0.06956238 0.88629886 0.64391789 0.79265382]]

 [[0.34392427 0.32651754 0.62271465 0.25899941]
  [0.92127365 0.7282549  0.54475628 0.65788358]
  [0.15946414 0.09530647 0.90702823 0.93527825]
  [0.82437082 0.83636159 0.45417007 0.66531498]
  [0.58875299 0.84922008 0.02940187 0.80543824]
  [0.60077931 0.38444536 0.05307105 0.21967469]]

 [[0.09733183 0.95245529 0.8835273  0.18672287]
  [0.58703478 0.05835447 0.71611783 0.58110579]
  [0.94899443 0.80031181 0.7674825

In [ ]:
a=np.ones([4,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.ones([6,4,5])
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
