<a href="https://colab.research.google.com/github/N-Vincentia-Harshini-4/FML-lab/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a=np.eye(2)
print(a)


[[1. 0.]
 [0. 1.]]


In [8]:
a=np.full((4,3),4)
print(a)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [9]:
a=np.random.random((2,4))
print(a)

[[0.89739954 0.76619436 0.9687894  0.91965571]
 [0.82112093 0.83081824 0.55783433 0.17590832]]


In [13]:
a = np.array([[2,4,6], [1,3,5], [6,8,9]])
b=a[:1]
print(b)


[[2 4 6]]


In [16]:
a = np.array([[2,4,6], [1,3,5], [6,8,9]])
b=a[1:2]
print(b)

[[1 3 5]]


In [23]:
print(a[0, 2])
b[0, 0] = 20
print(a[0, 2])
print(a)
print(b)

6
6
[[ 2  4  6]
 [20  3  5]
 [ 6  8  9]]
[[20  3  5]]


In [24]:
print(b)

[[20  3  5]]


In [25]:
print(a)

[[ 2  4  6]
 [20  3  5]
 [ 6  8  9]]


In [28]:
a=np.array([[1,3,5,7], [2,4,6,8], [1,4,6,7]])
print(a)

[[1 3 5 7]
 [2 4 6 8]
 [1 4 6 7]]


In [29]:
x=a[2, :]
print(x)


[1 4 6 7]


In [31]:
x=a[1:1, :]
print(a)

[[1 3 5 7]
 [2 4 6 8]
 [1 4 6 7]]
